

//login
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

//claim
export const CLAIM_REQUEST = 'CLAIM_REQUEST';
export const CLAIM_SUCCESS = 'CLAIM_SUCCESS';
export const CLAIM_FAIL = 'CLAIM_FAIL';
export const CLAIM_TARGET_SUCCESS = 'CLAIM_TARGET_SUCCESS';
export const CAR_CLAIM_REQUIREMENT_SUCCESS = 'CAR_CLAIM_REQUIREMENT_SUCCESS';

//buy
export const OPEN_CHANGE_FEE = 'OPEN_CHANGE_FEE';
export const CLOSE_PACKAGE_NULL = 'CLOSE_PACKAGE_NULL';
export const CLOSE_WEB_PAY = 'CLOSE_WEB_PAY';
export const WEB_PAY_SUCCESS = 'WEB_PAY_SUCCESS';
export const GET_PAY_SUCCESS = 'GET_PAY_SUCCESS';
export const CONTRACT_INFO_SUCCESS = 'CONTRACT_INFO_SUCCESS';
export const BUY_REQUEST = 'BUY_REQUEST';
export const BUY_SUCCESS = 'BUY_SUCCESS';
export const BUY_FAIL = 'BUY_FAIL';
//notify
export const NOTIFY_REQUEST = 'NOTIFY_REQUEST';
export const NOTIFY_SUCCESS = 'NOTIFY_SUCCESS';
export const NOTIFY_FAIL = 'NOTIFY_FAIL';

//car
export const CAR_REQUIREMENT_REQUEST = 'CAR_REQUIREMENT_REQUEST';
export const CAR_MODAL_CHECK_PRICE = 'CAR_MODAL_CHECK_PRICE';
export const CAR_SET_PATH_CORNER = 'CAR_SET_PATH_CORNER';
export const CAR_EXCLUSION_SUCCESS = 'CAR_EXCLUSION_SUCCESS';
export const CAR_SET_PROFILE_ID = 'CAR_SET_PROFILE_ID';
export const CAR_PACKAGE_REQUEST = 'CAR_PACKAGE_REQUEST';
export const CLOSE_CONTRACT_SUCCESS = 'CLOSE_CONTRACT_SUCCESS';
export const SAVE_CONTRACT_SUCCESS = 'SAVE_CONTRACT_SUCCESS';
export const CAR_CHECK_PRICE_REQUEST = 'CAR_CHECK_PRICE_REQUEST';
export const SET_PRODUCER = 'SET_PRODUCER';
export const CAR_FAIL = 'CAR_FAIL';
export const CAR_REQUEST = 'CAR_REQUEST';
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';
export const SET_PRICE = 'SET_PRICE';
export const ADD_PRICE = 'ADD_PRICE';
export const CAR_UPDATE_IMAGE = 'CAR_UPDATE_IMAGE';
export const CAR_REQUIREMENT_SUCCESS = 'CAR_REQUIREMENT_SUCCESS';
export const CAR_PACKAGE_SUCCESS = 'CAR_PACKAGE_SUCCESS';
export const CAR_PACKAGE_FAIL = 'CAR_PACKAGE_FAIL';
export const CAR_YEAR_SUCCESS = 'CAR_YEAR_SUCCESS';
export const CAR_CHECK_PRICE_SUCCESSS = 'CAR_CHECK_PRICE_SUCCESSS';
export const CAR_CHECK_PRICE_FAIL = 'CAR_CHECK_PRICE_FAIL';
export const CAR_GET_PRICE_SUCCESS = 'CAR_GET_PRICE_SUCCESS';

export const CAR_SEAT_SUCCESS = 'CAR_SEAT_SUCCESS';
export const CAR_MODEL_SUCCESS = 'CAR_MODEL_SUCCESS';
export const CAR_PRODUCER_REQUEST = 'CAR_PRODUCER_REQUEST';
export const CAR_PRODUCER_SUCCESS = 'CAR_PRODUCER_SUCCESS';
export const CAR_PRODUCER_FAIL = 'CAR_PRODUCER_FAIL';